// <auto-generated />
using System;
using CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001114338_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categorys");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Comfortable Passenger Vehicles",
                            CategoryName = "Sedan"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Sprt utility Vehicles",
                            CategoryName = "SUV"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "Compact Practical Vehicles",
                            CategoryName = "HatchBack"
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.HasIndex("DriverLicenseNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            DriverLicenseNumber = "DL100001",
                            Email = "ahmed.hassan@example.com",
                            FullName = "Ahmed Hassan",
                            PhoneNumber = "01010000001"
                        },
                        new
                        {
                            CustomerId = 2,
                            DriverLicenseNumber = "DL100002",
                            Email = "mona.adel@example.com",
                            FullName = "Mona Adel",
                            PhoneNumber = "01010000002"
                        },
                        new
                        {
                            CustomerId = 3,
                            DriverLicenseNumber = "DL100003",
                            Email = "omar.khaled@example.com",
                            FullName = "Omar Khaled",
                            PhoneNumber = "01010000003"
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.CustomerProfile", b =>
                {
                    b.Property<int>("CustomerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerProfileId"));

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CustomerCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CustomerDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNationality")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CustomerProfileId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomersProfiles");

                    b.HasData(
                        new
                        {
                            CustomerProfileId = 1,
                            CustomerAddress = "12 Nile St.",
                            CustomerCity = "Cairo",
                            CustomerDateOfBirth = new DateTime(1992, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            CustomerNationality = "Egyptian"
                        },
                        new
                        {
                            CustomerProfileId = 2,
                            CustomerAddress = "25 Tahrir St.",
                            CustomerCity = "Giza",
                            CustomerDateOfBirth = new DateTime(1995, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            CustomerNationality = "Egyptian"
                        },
                        new
                        {
                            CustomerProfileId = 3,
                            CustomerAddress = "18 El Nasr St.",
                            CustomerCity = "Cairo",
                            CustomerDateOfBirth = new DateTime(1988, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            CustomerNationality = "Egyptian"
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeFullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmployeeHireDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeePhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmployeePosition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeEmail")
                        .IsUnique();

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            EmployeeEmail = "mostafa.nabil@autodrive.com",
                            EmployeeFullName = "Mostafa Nabil",
                            EmployeeHireDate = "2021-01-10",
                            EmployeePhoneNumber = "01010000001",
                            EmployeePosition = "Sales Manager"
                        },
                        new
                        {
                            EmployeeId = 2,
                            EmployeeEmail = "aya.emad@autodrive.com",
                            EmployeeFullName = "Aya Emad",
                            EmployeeHireDate = "2021-04-15",
                            EmployeePhoneNumber = "01010000002",
                            EmployeePosition = "Sales Consultant"
                        },
                        new
                        {
                            EmployeeId = 3,
                            EmployeeEmail = "hassan.ali@autodrive.com",
                            EmployeeFullName = "Hassan Ali",
                            EmployeeHireDate = "2021-02-20",
                            EmployeePhoneNumber = "01010000003",
                            EmployeePosition = "Sales Consultant"
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Sale");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            CustomerId = 1,
                            EmployeeId = 1,
                            Notes = "Complete Sale.",
                            PaymentMethod = "Bank Transfer",
                            SaleDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalePrice = 1750000m,
                            VehicleId = 1
                        },
                        new
                        {
                            SaleId = 2,
                            CustomerId = 2,
                            EmployeeId = 2,
                            Notes = "Complete Sale.",
                            PaymentMethod = "Bank Transfer",
                            SaleDate = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalePrice = 1850000m,
                            VehicleId = 2
                        },
                        new
                        {
                            SaleId = 3,
                            CustomerId = 3,
                            EmployeeId = 3,
                            Notes = "Complete Sale.",
                            PaymentMethod = "Cash",
                            SaleDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalePrice = 510000m,
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FuelType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<decimal>("VehiclePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            CategoryId = 1,
                            Color = "White",
                            FuelType = "Petrol",
                            Make = "Toyota",
                            Mileage = 12000,
                            Model = "Corolla",
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "VIN00000000000001",
                            VehiclePrice = 650000m,
                            Year = 2024
                        },
                        new
                        {
                            VehicleId = 2,
                            CategoryId = 2,
                            Color = "Black",
                            FuelType = "Petrol",
                            Make = "Hyundai",
                            Mileage = 18000,
                            Model = "Elantra",
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "VIN00000000000002",
                            VehiclePrice = 590000m,
                            Year = 2023
                        },
                        new
                        {
                            VehicleId = 3,
                            CategoryId = 3,
                            Color = "Gray",
                            FuelType = "Petrol",
                            Make = "Kia",
                            Mileage = 9000,
                            Model = "Sportage",
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "VIN00000000000003",
                            VehiclePrice = 980000m,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.CustomerProfile", b =>
                {
                    b.HasOne("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Customer", "Customer")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.CustomerProfile", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Sale", b =>
                {
                    b.HasOne("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Employee", "Employee")
                        .WithMany("Sales")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Vehicle", "Vehicle")
                        .WithMany("Sales")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Vehicle", b =>
                {
                    b.HasOne("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Category", "Category")
                        .WithMany("Vehicles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Category", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Customer", b =>
                {
                    b.Navigation("CustomerProfile")
                        .IsRequired();

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Employee", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM_Demo_1.Models.Vehicle", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
